### ISSUE TITLE
Carraige returns or complex regex

### ISSUE THREAD

**Issue by nigeljohnson73** [tholu/php-packer#12]
I appreciate this hasn't been updated in 10 years, but  I still use it. I've been noticing a few flakey bits that I tend to just work around. 

Also, if I put the following in various places throughout my code:

`console.log("Return character: " + ("\n".charCodeAt(0)));`

Without packing it correctly shows 10. With packing, it shows 124 or 115 in 2 separate places I checked. Similarly, the following cause the packer to pack, but then the JS throws various syntax errors when unpacking:

`var regexp = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;`

`string = string.replace(/\r\n/g, "\n");`

**Comment by tholu** [comment]
@nigeljohnson73 Can you share the full code you are using to pack it (including options), thanks!

**Comment by tholu** [comment]
@nigeljohnson73 Please provide full code, otherwise this issue will be closed due to inactivity.

**Comment by tholu** [comment]
Closed due to inactivity.
