### ISSUE TITLE
Is there a need for eval???

### ISSUE THREAD

**Issue by LukeMadhanga** [tholu/php-packer#14]
Everyone everywhere says that `eval` is evil. Why then does the code have eval at the end, as is there a need for it?

**Comment by C0nw0nk** [comment]
I think if you remove eval the code won't evaluate and run and get the output you want.

Example

Original code
```
alert("lol");
```

Packed code working with eval evaluating to get desired output.
```
eval(function(p,a,c,k,e,r){e=String;if(!''.replace(/^/,String)){while(c--)r[c]=k[c]||c;k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('0("1");',2,2,'alert|lol'.split('|'),0,{}))
```

Packed code without eval.
```
function(p,a,c,k,e,r){e=String;if(!''.replace(/^/,String)){while(c--)r[c]=k[c]||c;k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('0("1");',2,2,'alert|lol'.split('|'),0,{});
```

Packed code working without eval inside a function that will run to get the output desired.
```
(function(p,a,c,k,e,r){e=String;if(!''.replace(/^/,String)){while(c--)r[c]=k[c]||c;k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('0("1");',2,2,'alert|lol'.split('|'),0,{}))();
```

It may not work under all circumstances my simple test with the function i demonstrated works for me on Firefox but other browsers and different more complex code may cause unexpected results test i guess.


Replace eval with empty function.

```
eval( packed code )
```
Becomes this
```
( packed code )();
```

**Comment by tholu** [comment]
As @C0nw0nk explained, the `eval()` is necessary for the packer to work.
