### ISSUE TITLE
trailing slash `\` breaks the output on UNIX

### ISSUE THREAD

**Issue by Ciki** [tholu/php-packer#15]
Hi @tholu, what does [this line](https://github.com/tholu/php-packer/blob/master/src/Packer.php#L129) particularly?

I have been hunting down a bug caused by this line for a day.. if multiline separator `\` is used in javascript the regexp got confused by that if having `\\` as separator. ~~Can we go with [default separator](https://github.com/tholu/php-packer/blob/master/src/Packer.php#L548) `` (empty) or does this `\\` have a special purpose here? Or to be safe can we use `@@` as separator (should not interfere with anything)?~~

```js
/* just a test \
*/
"test".replace(/test\[.*\]/gi, ''));
```

or

```js
$('<div class="progress"> \
</div>');
"test".replace(/test\[.*\]/gi, ''));
```

the trailing `\` can be even commented out (or not) and breaks the output

expected
```
"test".replace(/test\[.*\]/gi, ''));
```

actual
```
"test".replace(/test\].*\x/gi,''));
```

Please note, this happens only with UNIX line ending style, not DOS

**Comment by tholu** [comment]
@Ciki I'm not the original author of this code, I just packed it for composer and did some minor extensions. If you can, I would avoid the multiline separator altogether to solve this.

**Comment by Ciki** [comment]
OK, I did just that
