### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '}'

### ISSUE THREAD

**Issue by darrenmerrett** [tholu/php-packer#17]
I've used the packer on a number of projects and I really like it. I've seen a few people report "Unexpected token" and I've recently ran into this problem myself.

I narrowed it down to this piece of my code below

`functions start (delay) {
		var start = new Date().getTime();
		while (new Date().getTime() < start + delay);
},`

The "while" loop is the issue for me. This seems to be valid code, although it's short hand for 

`while (new Date().getTime() < start + delay){};`

The packer packs it like this

`functions start (delay) {var start = new Date().getTime();while (new Date().getTime() < start + delay)},`

A very subtle difference, the ';' semi colon after the closing bracket on my while loop has been omitted by the packer, (which i agree with, no point in extra characters when you're trying to condense something.

Without the closing bracket the code is not valid and throws the error Uncaught SyntaxError: Unexpected token '}'

Easy solution for me.... changed my code to:

`functions start (delay) {
		var start = new Date().getTime();
		while (new Date().getTime() < start + delay){}
},`

... And everything now works fine.

I hope this helps someone with a similar problem.

**Comment by tholu** [comment]
@darrenmerrett Thanks for sharing your solution! I only pack the existing obfuscation mechanism for composer, so there are some situations where code needs to be explicit and the obfuscator fails with valid code.
