### ISSUE TITLE
Illegal return statement

### ISSUE THREAD

**Issue by ghost** [tholu/php-packer#3]
when their is return false statement then it show Illegal return statement

**Comment by tholu** [comment]
Do you have an example?

**Comment by ghost** [comment]
require '../src/Packer.php';
error_reporting(E_ALL);
$js = ' var i = 5;if(i == 5){document.getElementById("demo").innerHTML = "Hello World"; return false;}alert("hello");';
$packer = new Tholu\Packer\Packer($js, 62, true, true);
$packed_js = $packer->pack();
echo $packed_js;

**Comment by tholu** [comment]
Your example is incomplete, you are missing the function definition from which you are returning. Perhaps this is also the problem?

**Comment by tholu** [comment]
Closed because of inactivity.
