### ISSUE TITLE
_specialChars error 2

### ISSUE THREAD

**Issue by tamaranga** [tholu/php-packer#5]
input:

``` js
var formManager=(function(){
    var _prefix = "zzz";
    var _test = $("#"+_prefix+"_child");
    var _output = "$this->";
}());
```

output:

``` js
var formManager=(function(){var _0="zzz";var _1=$("#"+_0+"_2");var _3="t->";}());
```

problem is in modified strings:
`"_child"` => `"_2"`
`"$this->"` => `"t->"`

definitely it is possible to do in this way:
`"$$$$$$_child"`
`"$$$$$this->"`

:) but it's so simple to make a mistake in preparing a big script.
Maybe we can find another way?

**Comment by tholu** [comment]
Try setting `$specialChars` to false.

**Comment by tamaranga** [comment]
But I need it, the main goal is obfuscation :)

**Comment by tholu** [comment]
Try using `"_"` and `"$"` and concat them with `+` instead of using strings that look like flagged variables.

``` js
var formManager=(function(){
    var _prefix = "zzz";
    var _test = $("#"+_prefix+"_"+"child");
    var _output = "$"+"this->";
}());
```

**Comment by tamaranga** [comment]
Concerning "$" - thank you, this is a solution.
Interesting that this string `"x_child"` will stay the same, so maybe you should add in regular (replacing) expression check if there is no `"` and `'` leftside (for "private variables" case only).

**Comment by tholu** [comment]
Sorry, I can't follow - you did not want `_child` to be obfuscated, as stated in the original post. My example should work fine for that.

**Comment by tamaranga** [comment]
Your solution is fine, for both my cases.
But in general, as a suggestion, maybe "_child" situation should be fixed in a way I described. In parser.

**Comment by tholu** [comment]
In general, the default for `$specialChars` is false - good enough for me.
