### ISSUE TITLE
Arabic string obfuscation

### ISSUE THREAD

**Issue by yazan-bawab** [tholu/php-packer#6]
when the JavaScript function have messages in Arabic and execute the packer, it's going to interact with some Arabic words as they are a reserved word in the JavaScript code and don't change them to its equivalent in the encoded array so when the packer finish his job it will come with an special character that could not be  represented in the JavaScript so the JavaScript will not work.

**Comment by tholu** [comment]
Do you have an example you can share?

**Comment by tholu** [comment]
Closed because no example given.
