### ISSUE TITLE
How to prevent decoding of encoded function?

### ISSUE THREAD

**Issue by sksar** [tholu/php-packer#8]
I want to use this packer, (obfuscator) to encode and obfuscate my javascript code, but i don't want others to be able to decode it whatsoever,,,,,,,   As this packer is very common online, anyone with my code can get into it by using the official packer decoder.. how can i prevent that?

I guess i need to make certain changes into the code, but where and how??

**Comment by tholu** [comment]
It is not possible to fully prevent that.
