### ISSUE TITLE
Fatal error:  Class 'Packer' not found

### ISSUE THREAD

**Issue by Shababsoft** [tholu/php-packer#9]
I have used composer to download the package but when I am getting the below error message when trying to user the packer.

`Fatal error:  Class 'Packer' not found in test.php`

Php code:
`require_once 'vendor/autoload.php';
$myPacker = new Packer($jquery, 'Normal', true, false, true);`

**Comment by tholu** [comment]
This seems weird. Are you sure that composer installed the package correctly? Is the package in your `vendor` folder?

**Comment by Shababsoft** [comment]
Yes, it is in the vendor folder but I couldn't find the Packer class in the autoload composer classes map file.

**Comment by tholu** [comment]
Seems more like a `composer` issue to me.

**Comment by Shababsoft** [comment]
"psr-4": {
     			"Mpdf\\": "src/"
		},

**Comment by Shababsoft** [comment]
"psr-4": {
                "Mpdf\": "src/"
        },

**Comment by Shababsoft** [comment]
I was thinking it may be due to "/" at the end of src

**Comment by tholu** [comment]
I updated the README, this should work:

```
$packer = new Tholu\Packer\Packer($js, 'Normal', true, false, true);
```
